//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaceutskaKuca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class baza_znanja
    {
        public int id { get; set; }
        public string naziv_incidenta { get; set; }
        public string rjesenje { get; set; }
        public int id_k { get; set; }
    
        public virtual kategorija kategorija { get; set; }
    }
}
