//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaceutskaKuca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dostupnost
    {
        public int id { get; set; }
        public int id_s { get; set; }
        public int id_m { get; set; }
        public int procenat { get; set; }
    
        public virtual servis servis { get; set; }
        public virtual mjesec mjesec { get; set; }
    }
}
