//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaceutskaKuca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class incident
    {
        public int id { get; set; }
        public Nullable<System.DateTime> vrijemePrijave { get; set; }
        public string naziv { get; set; }
        public string opis { get; set; }
        public Nullable<int> Kategorija_id { get; set; }
        public string prioritet { get; set; }
        public string status { get; set; }
        public int Korisnik_id { get; set; }
        public string Napomena_M { get; set; }
        public string Napomena_K { get; set; }
    
        public virtual kategorija kategorija { get; set; }
        public virtual korisnik korisnik { get; set; }
    }
}
