//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaceutskaKuca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class korisnikxedukacija
    {
        public int id { get; set; }
        public Nullable<int> id_k { get; set; }
        public Nullable<int> id_e { get; set; }
        public Nullable<int> odobreno { get; set; }
    
        public virtual edukacija edukacija { get; set; }
        public virtual korisnik korisnik { get; set; }
    }
}
